export const sensitiveFields = Object.freeze([
  'careNotes',
  'addressText',
  'locationShareUrl',
  'addresses.text',
  'cnicNumber',
  'cnicDocumentRef',
  'cnicDocRef',
  'interviewRecordingRef',
  'consentRecordingRef',
  'recordingRef',
  'emergencyContactNotes',
  'visitNotes',
  'note',
  'passwordHash',
  'refreshTokenHash',
  'tokenHash',
]);
